### ISSUE TITLE
Spec test works for final refactored version, but fails earlier versions.

### ISSUE THREAD

**Issue by smithWEBtek** [learn-co-curriculum/rails-form_tag-readme#11]
This portion of the lab has you edit the spec file as it refers to the ID attribute. 
In the early parts of the lab, the tests fail because spec file as written, is trying to find either an ID= "title" or content="title (both work).    The code in the early parts of the lab, show ID = post_title and content="post_content" (both fail).   If you change either of them to "title" or "content" respectively, the tests pass. 

So, we should either change the earlier code examples in the lab to "test" and/or "content" and then remove the last section where you correct the spec file, or remove the "correcting of the spec file" pasted below:

This is all working on the page, however it broke some of our tests since it streamlined the ID attribute in the form, so let's update our spec:
fill_in 'title', with: "My post title"
fill_in 'description', with: "My post description"
Running the specs again and now we're back to everything passing and you now know how to build a Rails form from scratch and refactor it using Rails form helper methods, nice work!

**Comment by mendelB** [comment]
Thanks for raising this issue @smithWEBtek !
