### ISSUE TITLE
Tests already complete - do not match in some sections of lesson

### ISSUE THREAD

**Issue by steveafrost** [learn-co-curriculum/rails-form_tag-readme#12]
Since the tests are already completely written when this lab is forked and cloned down, the middle sections of the lab fail. The tests are looking for a field named "description" but when we manually write out the HTML, the lab says to name it "post_description" and the test fails. In the lab it says the test passed but it didn't.

Could be resolved by including no test with the lesson and letting the student write the test as the lab goes along.

Hope that helps!

**Comment by mendelB** [comment]
Thanks for raising this @steveafrost !
