### ISSUE TITLE
Cannot render console from (<IP address here>)! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255

### ISSUE THREAD

**Issue by DanL12186** [learn-co-curriculum/rails-form_tag-readme#14]
Got this error upon submit rather than the authentication token error. 

Entering config.web_console.whitelisted_ips = (IP address here) while the server was running seemed to fix it and get me to the authentication error (although the server still complains in the IDE's console about the request).

Unsure if others will have this issue, running OS X 10.9.5. Issue presented in both Chrome 57 and FireFox 52.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
