### ISSUE TITLE
rake was not running properly, neither was rspec

### ISSUE THREAD

**Issue by Nitro152** [learn-co-curriculum/rails-form_tag-readme#15]
I cloned this lab and tried to run learn/bundle exec rspec and it would not return anything.
It seems like there was an issue with the gem version maybe. I deleted the gemfile.lock and reran bundle install and this corrected the issue. I can run rspec and rake now.

**Comment by curiositypaths** [comment]
Hi there,

Thank you for taking the time to contribute to our curriculum. We will update the Gemfile.lock file to correct the specs execution.

Thanks! 💙
