### ISSUE TITLE
Inconsistency between this readme and later labs

### ISSUE THREAD

**Issue by jmburges** [learn-co-curriculum/rails-form_tag-readme#18]
In this readme we nest the params in the post hash. Later in this lab https://github.com/learn-co-curriculum/rails-create-action-lab we don't nest them!

**Comment by drakeltheryuujin** [comment]
Hi there,

Thank you for your feedback! We'll take this information into consideration in upcoming releases of this curriculum.

As always, thanks for contributing! 💙
