### ISSUE TITLE
no learn specs

### ISSUE THREAD

**Issue by BrittanyTinnin** [learn-co-curriculum/rails-form_tag-readme#19]
this readme is walking through as if there are tests in the code along, but there are no learn specs

**Comment by joanrig** [comment]
6 months later, same problem.
a classmate provided this link to our cohort: https://github.com/BebopVinh/spec-for-rails-form-tag-codealong

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
