### ISSUE TITLE
404

### ISSUE THREAD

**Issue by onyoo** [learn-co-curriculum/rails-form_tag-readme#2]
https://github.com/learn-co-students/rails-form_tag-readme-v-000

**Comment by AnnJohn** [comment]
Hi @onyoo sorry again for the issues with all the lesson deployments. this and all the other ones should now be fixed. thanks!

**Comment by onyoo** [comment]
Hey @AnnJohn, please don't worry about it! I know you guys have a lot on your plate. Anyway, I really love the curriculum! You guys are doing an awesome job!
