### ISSUE TITLE
Student needs to run rails generate rspec:install

### ISSUE THREAD

**Issue by ValerieHMoore** [learn-co-curriculum/rails-form_tag-readme#20]
The lab says to create a test file, but you'll get an error that indicates 'rails helper' isn't found unless you run rails generate rspec:install in the terminal. Also the file path the lab says to create for the tests is specs/features/post_spec.rb, however when you do run rails generate rspec:install, your path will be spec/features/post_spec.rb -- spec without the "s" on the end.

Two ways to fix this would be:
1. Add the necessary files to the lab, so when you clone the lab, you get them
2. Direct the student to run rails generate rspec:install in the terminal

Thank you.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
