### ISSUE TITLE
This is difficult to follow along

### ISSUE THREAD

**Issue by helloamandamurphy** [learn-co-curriculum/rails-form_tag-readme#22]
It would be helpful to have the `rails generate rspec:install` command in the beginning of the lab to create the spec directory. In the lab it also refers to the `specs` folder, but it should be singular `spec` if you use the first command.

These labs where you are copy and pasting in the spec and the code are always extremely confusing. I always have to ask help from a coach on the "ReadMe" lessons because they are almost always missing a step or are confusing. If you want to teach specs, have their own module. I think everyone would benefit from it.

-A

**Comment by drakeltheryuujin** [comment]
Hi there,

Thank you for your feedback! We'll take this information into consideration in upcoming releases of this curriculum.

As always, thanks for contributing! 💙
