### ISSUE TITLE
Not Showing as Completed Lab in Curriculum List or Profile

### ISSUE THREAD

**Issue by helloamandamurphy** [learn-co-curriculum/rails-form_tag-readme#23]
Hey there,
This lab is showing as complete on my "green flag", but is not checking off under the Curriculum drop down menu or on my profile page. I know you're having issues with lessons not showing as complete, so I wanted to message about this error. I'm attaching screenshots.

Best,
A

<img width="1440" alt="Screen Shot 2019-05-03 at 2 02 44 PM" src="https://user-images.githubusercontent.com/40896525/57156791-deb95080-6dac-11e9-8e23-5dff513d9824.png">
<img width="1440" alt="Screen Shot 2019-05-03 at 2 02 57 PM" src="https://user-images.githubusercontent.com/40896525/57156793-e1b44100-6dac-11e9-9a7a-2ef0f367178b.png">
<img width="1440" alt="Screen Shot 2019-05-03 at 2 04 43 PM" src="https://user-images.githubusercontent.com/40896525/57156796-e4169b00-6dac-11e9-8ec7-c3cf77b639ca.png">
<img width="1440" alt="Screen Shot 2019-05-03 at 2 05 43 PM" src="https://user-images.githubusercontent.com/40896525/57156801-e8db4f00-6dac-11e9-9d34-ad849832e40b.png">

**Comment by drakeltheryuujin** [comment]
Hi there! This request sounds like a problem with the Learn platform.

Our product team can help you with this. You can reach them at support@learn.co.

[Raising issues on GitHub][raise], like you've done here should happen when
there are problems with the curriculum itself (doesn't work, throws a Ruby
error, etc.)

If, on the other hand, we've misunderstood the purpose of this request, please
re-open this issue, provide any additional information you can to clarify our error,
and we will try to find a fix.

[raise]: http://help.learn.co/improving-learn/contributing-to-lessons/raising-an-issue-with-a-lab-or-lesson
