### ISSUE TITLE
There is no Spec folder

### ISSUE THREAD

**Issue by rossmawd** [learn-co-curriculum/rails-form_tag-readme#24]
The readme says there is a Spec file. But there is none

**Comment by cdallasanta** [comment]
To add more info:

Following the readme, line 42 tells us to require 'rails_helper', but no file exists. Running 1rails g rspec:install1 fixes the issue, but this step was not instructed in the Readme, and only passingly mentioned in a previous lesson as a step they had performed before the student encounters the lab (which also doesn't seem to be the case, an issue is raised on that lesson as well).

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
