### ISSUE TITLE
I can't get the first test to pass--rspec and routes issue

### ISSUE THREAD

**Issue by wkdewey** [learn-co-curriculum/rails-form_tag-readme#33]
When I do the first spec and put`resources :posts, only: [:index, :new]` in my routes.rb file, the initial error doesn't go away, even though "rails routes" shows that the route new_post is there: 
`Failures:

  1) new post ensures that the form route works with the /new action
     Failure/Error: visit new_post_path

     NameError:
       undefined local variable or method `new_post_path' for #<RSpec::ExampleGroups::NewPost:0x00007f9d5fc656c0>
     # ./spec/post_spec.rb:5:in `block (2 levels) in <top (required)>'`

My tech coach couldn't solve this, I wonder if the answer is here: https://stackoverflow.com/questions/21478384/rspec-test-custom-route-path-results-in-not-recognized-by-rspec-undefined-loc.
"You cannot access named route from your tests unless you add this to spec_helper.rb

```
Rspec.configure do |config|
  config.include Rails.application.routes.url_helpers
  ...
end
```
"

Putting that line in spec_helper just gives me an error, however. NameError:
  uninitialized constant Rails.

**Comment by wkdewey** [comment]
If I start up a rails server, the code works. So I think the problem is with the rspec setup.

**Comment by gnappo1** [comment]
The issue is that you likely created the test file not respecting the path suggested: `# spec/features/post_spec.rb`.
If inside the `spec` folder you create a folder called `features` and move the `post_spec.rb` file in there, the tests will now have access to the route helpers! 🤓
