### ISSUE TITLE
spec is set for end of lab result instead of middle result

### ISSUE THREAD

**Issue by pajamaw** [learn-co-curriculum/rails-form_tag-readme#8]
In the middle of the codealong they ask you to put post_title and post_description into both the id and name tags in order to get the lab to pass. But the spec has been premade for the end of the lab when you're using form helpers. so you have to put title and description into the id/name tags in the middle of the lab to get the spec to pass as it should.

**Comment by pletcher** [comment]
Thanks for opening this issue.

Going through the README, the spec _shouldn't_ pass until you get to the end -- it failing in the middle is okay. However, I've added a note about modifying the spec itself as you go through the code-along.
